server:
  port: 9090

spring:
  application:
    name: ecommerce

  jpa:
    hibernate:
      ddl-auto: create #change to validate after first exec
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
